# Generated by Django 6.0.5 on 2026-05-26 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0003_agency_auth_config'),
        ('services', '0002_alter_serviceendpoint_endpoint_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='agencies.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('SERVICE', 'Service Call'), ('APPROVAL', 'Approval'), ('CONDITIONAL', 'Conditional'), ('NOTIFICATION', 'Notification'), ('MANUAL_REVIEW', 'Manual Review'), ('DELAY', 'Delay')], default='SERVICE', max_length=50)),
                ('name', models.CharField(blank=True, help_text='Display name for this step', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text="JSON logic: {'operator': 'AND', 'rules': [{'field': 'previous_response.status', 'operator': 'eq', 'value': 'success'}]}")),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('retry_policy', models.JSONField(blank=True, default=dict, help_text="{'max_retries': 3, 'retry_delay_seconds': 5, 'backoff_multiplier': 2}")),
                ('requires_approval', models.BooleanField(default=False)),
                ('approver_roles', models.JSONField(blank=True, default=list, help_text="['AGENCY_ADMIN', 'OPERATIONS_OFFICER']")),
                ('config', models.JSONField(blank=True, default=dict, help_text='Step-specific config: notification template, delay duration, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_steps', to='services.serviceendpoint')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
