# Generated by Django 6.0.5 on 2026-05-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowstep',
            name='execution_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual Step-by-Step'), ('AUTO', 'Automatic')], default='MANUAL', max_length=50),
        ),
    ]
