# Generated by Django 6.0.5 on 2026-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_workflowstep_execution_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflowstep',
            name='execution_mode',
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_sequential',
            field=models.BooleanField(default=False, help_text='If True, steps must be completed in order'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='is_repeatable',
            field=models.BooleanField(default=False, help_text='Allow multiple submissions for this step'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='max_repetitions',
            field=models.PositiveIntegerField(default=1, help_text='Maximum allowed submissions (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='min_repetitions',
            field=models.PositiveIntegerField(default=1, help_text='Minimum required submissions'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='approver_roles',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='conditions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='retry_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
