# Generated by Django 6.0.5 on 2026-05-26 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0003_agency_auth_config'),
        ('executions', '0001_initial'),
        ('services', '0002_alter_serviceendpoint_endpoint_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('WORKFLOW_COMPLETED', 'Workflow Completed'), ('WORKFLOW_FAILED', 'Workflow Failed'), ('STEP_APPROVAL', 'Step Approval Required'), ('SERVICE_DOWN', 'Service Down'), ('AGENCY_OFFLINE', 'Agency Offline'), ('EXECUTION_WAITING', 'Execution Waiting'), ('SYSTEM_ALERT', 'System Alert')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencies.agency')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.serviceendpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('workflow_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='executions.workflowexecution')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
