# Generated by Django 6.0.5 on 2026-06-02 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_agency_auth_config'),
        ('collaboration', '0003_message_is_pinned'),
        ('executions', '0002_rename_approval_comment_executionstep_officer_notes_and_more'),
        ('notifications', '0001_initial'),
        ('services', '0004_remove_serviceendpoint_request_schema_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='collaboration.conversation'),
        ),
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Frontend route e.g. /requests/123', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('WORKFLOW_STARTED', 'Workflow Started'), ('WORKFLOW_COMPLETED', 'Workflow Completed'), ('WORKFLOW_FAILED', 'Workflow Failed'), ('WORKFLOW_REJECTED', 'Workflow Rejected'), ('WORKFLOW_CANCELLED', 'Workflow Cancelled'), ('STEP_COMPLETED', 'Step Completed'), ('STEP_FAILED', 'Step Failed'), ('STEP_APPROVAL', 'Step Approval Required'), ('TASK_ASSIGNED', 'Task Assigned'), ('TASK_UPDATED', 'Task Updated'), ('NEW_MESSAGE', 'New Message'), ('MENTION', 'Mention'), ('SERVICE_DOWN', 'Service Down'), ('SERVICE_UP', 'Service Up'), ('AGENCY_OFFLINE', 'Agency Offline'), ('AGENCY_ONLINE', 'Agency Online'), ('EXECUTION_WAITING', 'Execution Waiting'), ('CERTIFICATE_ISSUED', 'Certificate Issued'), ('SYSTEM_ALERT', 'System Alert'), ('FAILED_LOGIN', 'Failed Login Attempt'), ('PASSWORD_CHANGED', 'Password Changed')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'),
        ),
    ]
