# Generated by Django 6.0.5 on 2026-05-26 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0003_agency_auth_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('endpoint_url', models.URLField(help_text='Full URL or relative path appended to agency base_url')),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Default headers as key-value pairs')),
                ('request_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for request validation')),
                ('response_schema', models.JSONField(blank=True, default=dict, help_text='JSON Schema for response validation')),
                ('authentication_override', models.JSONField(blank=True, default=dict, help_text='Override agency auth for this endpoint (e.g., different API key)')),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('retry_count', models.PositiveIntegerField(default=3)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=50)),
                ('health_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline'), ('DEGRADED', 'Degraded'), ('MAINTENANCE', 'Maintenance')], default='OFFLINE', max_length=50)),
                ('version', models.CharField(blank=True, default='v1', max_length=50)),
                ('rate_limits', models.JSONField(blank=True, default=dict, help_text="Rate limit config: {'requests_per_minute': 60, 'burst': 10}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='agencies.agency')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Endpoint',
                'verbose_name_plural': 'Service Endpoints',
                'ordering': ['-created_at'],
            },
        ),
    ]
