# Generated by Django 6.0.5 on 2026-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceendpoint',
            name='endpoint_url',
            field=models.CharField(help_text='Full URL or relative path appended to agency base_url', max_length=500),
        ),
    ]
