# Generated by Django 6.0.5 on 2026-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_serviceendpoint_endpoint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceendpoint',
            name='field_definitions',
            field=models.JSONField(blank=True, default=list, help_text="Dynamic form fields: [\n            {'name': 'nin', 'label': 'National ID Number', 'type': 'text', 'required': true,\n             'placeholder': 'CM1234567890AB', 'help_text': '14-character NIN',\n             'validation_regex': '^CM[0-9]{10}[A-Z]{2}$', 'min_length': 14, 'max_length': 14,\n             'order': 1, 'is_sensitive': false, 'options': []}\n        ]"),
        ),
    ]
