# Generated by Django 6.0.5 on 2026-05-29 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_serviceendpoint_field_definitions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceendpoint',
            name='request_schema',
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='endpoint_url',
            field=models.URLField(help_text='Full URL or relative path appended to agency base_url'),
        ),
        migrations.AlterField(
            model_name='serviceendpoint',
            name='field_definitions',
            field=models.JSONField(blank=True, default=list, help_text="Dynamic form fields: [\n            {'name': 'nin', 'label': 'National ID Number', 'type': 'text', 'required': true,\n             'placeholder': 'CM1234567890AB', 'help_text': '14-character NIN',\n             'validation_regex': '^CM[0-9]{10}[A-Z]{2}$', 'min_length': 14, 'max_length': 14,\n             'order': 1, 'location': 'query', 'is_sensitive': false, 'options': []}\n        ]"),
        ),
        migrations.CreateModel(
            name='ServiceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Technical key, e.g. 'nin'", max_length=100)),
                ('label', models.CharField(help_text='Human readable label', max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('email', 'Email'), ('date', 'Date'), ('select', 'Select / Dropdown'), ('textarea', 'Textarea'), ('file', 'File Upload'), ('checkbox', 'Checkbox'), ('phone', 'Phone'), ('password', 'Password')], default='text', max_length=50)),
                ('required', models.BooleanField(default=False)),
                ('location', models.CharField(choices=[('query', 'Query Parameter'), ('body', 'Request Body'), ('header', 'HTTP Header'), ('path', 'URL Path Segment')], default='query', max_length=50)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.TextField(blank=True, help_text='Shown below the field in the UI')),
                ('default_value', models.CharField(blank=True, max_length=255)),
                ('validation_regex', models.CharField(blank=True, max_length=500)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('options', models.JSONField(blank=True, default=list, help_text="['Option 1', 'Option 2']")),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mask value in logs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_fields', to='services.serviceendpoint')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('service', 'name')},
            },
        ),
    ]
