# Generated by Django 6.0.5 on 2026-05-29 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditlogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditlog',
            name='request_payload',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='response_payload',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='http_method',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='new_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot after change'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot before change'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('READ', 'Read / Query'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed'), ('API_CALL', 'API Call'), ('WORKFLOW_STEP', 'Workflow Step'), ('TASK_UPDATE', 'Task Update'), ('PIN', 'Pin/Unpin'), ('FILE_UPLOAD', 'File Upload'), ('EXPORT', 'Data Export'), ('OTHER', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, help_text='Human-readable summary'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_id',
            field=models.CharField(blank=True, help_text='Primary key of affected object', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_name',
            field=models.CharField(blank=True, help_text="Human-readable name, e.g. 'Verify Citizen Identity'", max_length=255),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(help_text="Model name or endpoint name, e.g. 'ServiceEndpoint', 'login', 'nira-verify'", max_length=100),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', '-created_at'], name='auditlogs_a_user_id_c20b57_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', '-created_at'], name='auditlogs_a_action_821f9e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', '-created_at'], name='auditlogs_a_entity__8617c6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['status', '-created_at'], name='auditlogs_a_status_715bbc_idx'),
        ),
    ]
