# Generated by Django 6.0.5 on 2026-05-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0002_conversation_participants_message_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Pinned to top of conversation like WhatsApp'),
        ),
    ]
