# Generated by Django 6.0.5 on 2026-05-27 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='executionstep',
            old_name='approval_comment',
            new_name='officer_notes',
        ),
        migrations.RemoveField(
            model_name='executionstep',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='executionstep',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='executionstep',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='executionstep',
            name='request_payload',
        ),
        migrations.RemoveField(
            model_name='executionstep',
            name='response_payload',
        ),
        migrations.RemoveField(
            model_name='executionstep',
            name='response_status_code',
        ),
        migrations.RemoveField(
            model_name='executionstep',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='executionstep',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='workflowexecution',
            name='current_step_index',
        ),
        migrations.RemoveField(
            model_name='workflowexecution',
            name='execution_metadata',
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='applicant_contact',
            field=models.CharField(blank=True, help_text='Phone or email of applicant', max_length=255),
        ),
        migrations.AddField(
            model_name='workflowexecution',
            name='applicant_name',
            field=models.CharField(blank=True, help_text='Name of the citizen/applicant', max_length=255),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_execution_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='executionstep',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
        migrations.CreateModel(
            name='StepSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_data', models.JSONField(blank=True, default=dict)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('response_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('execution_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='executions.executionstep')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
