# Generated by Django 6.0.5 on 2026-05-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('agency_type', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='agency_logos/')),
                ('base_url', models.URLField(blank=True)),
                ('authentication_type', models.CharField(choices=[('API_KEY', 'API Key'), ('JWT', 'JWT'), ('OAUTH2', 'OAuth2'), ('BASIC_AUTH', 'Basic Auth'), ('CUSTOM', 'Custom')], default='API_KEY', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('OFFLINE', 'Offline'), ('SUSPENDED', 'Suspended'), ('MAINTENANCE', 'Maintenance')], default='ACTIVE', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
            },
        ),
    ]
