# Generated by Django 6.0.5 on 2026-05-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_agency_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='auth_config',
            field=models.JSONField(blank=True, default=dict, help_text='Authentication credentials/config'),
        ),
    ]
